packages:
  - "packages/utils"
  - "packages/tools"
  - "packages/delta"
  - "packages/ot-json"
  - "packages/core"
  - "packages/react"
  - "packages/plugin"
  - "packages/vue"
  - "examples/variable"
  - "examples/stream"
  - "examples/website"
