packages:
  - "packages/utils"
  - "packages/tools"
  - "packages/delta"
  - "packages/ot-json"
  - "packages/core"
  - "packages/react"
  - "packages/plugin"
  - "packages/vue"

  - "blocks/x-json"
  - "blocks/x-core"
  - "blocks/x-react"
  - "blocks/x-plugin"

  - "examples/variable"
  - "examples/stream"
  - "examples/website"
