name: deploy gh-pages

on:
  push:
    branches:
      - master

env:
  OUT_DIR: "examples/website/build"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: install node-v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"

      - name: install dependencies
        run: |
          node -v
          npm install -g pnpm@8.11.0
          pnpm install --registry=https://registry.npmjs.org/

      - name: build project
        run: |
          pnpm run --filter "@block-kit/website..." build
          matter="---\ntitle: Note\n---\n"
          echo -e "$matter" > $OUT_DIR/Notes.md
          cat NOTE.md >> $OUT_DIR/Notes.md

      - name: deploy project
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ env.OUT_DIR }}
