name: project testing

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: install node-v18
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.8"

      - name: install dependencies
        run: |
          node -v
          npm install -g pnpm@8.11.0
          pnpm install --registry=https://registry.npmjs.org/

      - name: build project
        run: |
          pnpm run --filter '*' build

      - name: lint typescript
        run: |
          pnpm run --filter '*' lint:ts

      - name: lint circular
        run: |
          npm -g install madge@8.0.0 --registry=https://registry.npmjs.org/
          pnpm run --filter '*' lint:circular

      - name: unit testing
        run: |
          export TZ="Asia/Shanghai"
          pnpm run --filter '*' test
